version: '3'
services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DEFAULT_PASSWORD=your_password
